version: "3.8"
services:
    postgres:
        image: postgres:15
        environment:
            POSTGRES_DB: nishlen_db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Auto-run SQL при первом старте
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d nishlen_db"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"

    minio:
        image: minio/minio:latest
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data

    auth:
        build: ./services/auth # Фикс пути
        ports:
            - "3001:3001"
        depends_on:
            postgres:
                condition: service_healthy # Ждёт готовности БД
        environment:
            DATABASE_URL: postgres://admin:secret@postgres:5432/nishlen_db
            JWT_SECRET: nishlen_secret
            NODE_ENV: development # Для ts-node
        restart: unless-stopped

    booking:
        build: ./services/booking
        ports:
            - "3002:3002"
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started
        environment:
            DATABASE_URL: postgresql://admin:secret@postgres:5432/nishlen_db # Фикс: postgresql
            REDIS_URL: redis://redis:6379
        restart: unless-stopped

volumes:
    postgres_data:
    minio_data:
